# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

#Constants
ProjectName = 'MVVMExample.xcodeproj'

platform :ios do

    desc "Build GIM Beta Release"
    lane :GIMBetaRelease do

    	increment_build_number
    	commit_version_bump
    	push_to_git_remote(tags:false)
  		
  	end

end
